### PR TITLE
Editor: Fix Addon Editor not loading when CustomCSS disabled

### LINKED ISSUE #864: [Bug] Edit button for Themes and Plugins freezes when opened
**Describe the Bug**
When the Edit button for a plugin or theme is clicked, the window to edit opens, but is blank and freezes on the window. The buttons are not functional and the window cannot be moved, resized, or closed. The edit window is blank and has no place for text input. 

**To Reproduce**
1. Open Discord settings
2. Click "Plugins" or "Themes"
3. Click the Edit icon (looks like a pencil) on any theme or plugin

**Expected Behavior**
When the Edit button is pressed,t he user should be able to edit the code of the theme or plugin to the user's desire. 

**Screenshots**
[https://drive.google.com/file/d/17W5gGd2dWirilQySEPpm_E2TvZonqfND/view?usp=sharing](url)

**Discord Version**
Discord Stable Build 89550
Windows 10 64-bit

**Additional Context**
BetterDiscord v1.1.1

### PR DESCRIPTION
**Pull request by QbDesu**
Fixes #864
This loads the editor unconditionall, even if CustomCSS is disabled and the Addon Editor is set to "Detached Window". I don't think the added complexity for loading it conditionally would be justified considering it's probably only a small fraction of the userbase this applies to.
On top of that it also would need to be loaded for #909 if that is to BetterDiscord.

### CODE REVIEW

**Comment by QbDesu** [comment]
WTH? I didn't close this.

**Comment by QbDesu** [comment]
Had to commit LF even though the `.eslintrc` specifies CRLF. Accidentally force pushed without commits which closed the PR.

File: renderer/src/modules/core.js [hunk 1]
```diff
@@ -59,6 +60,9 @@ export default new class Core {
         Logger.log("Startup", "Initializing ComponentPatcher");
         ComponentPatcher.initialize();
 
+        Logger.log("Startup", "Initializing Editor");
+        Editor.initialize();
```
Comment (rauenzi) [inline renderer/src/modules/core.js:64]: I think we should `await` this. Loading the editor was the reason there was the `await` on line 64:

```
if (module === "CustomCSS") await Builtins[module].initialize();
```

Not awaiting caused issues with subsequent `require` calls do to `require` being taken away and then returned asynchronously.

Comment (QbDesu) [reply renderer/src/modules/core.js]: Understood, and now that you mention it I'm a bit surprised that it didn't cause issues when testing it. It's fixed now.
and because you mentioned that it was the reason the CustomCSS modules had special treatment in Builtins initialization I also removed that, seems to work correctly and looking at the code nothing else there should break other places if it's not awaited.

Comment (QbDesu) [reply renderer/src/modules/core.js]: actually
```
Error: Failed to execute 'importScripts' on 'WorkerGlobalScope': The URL '../../../vs/language/typescript/tsWorker.js' is invalid.
    at d.load (workerMain.min.js:1)
    at f.load (workerMain.min.js:1)
```
I'll look into that in a minute.

Comment (rauenzi) [reply renderer/src/modules/core.js]: > CustomCSS modules had special treatment in Builtins initialization I also removed that

Sounds good to me

Comment (rauenzi) [reply renderer/src/modules/core.js]: > I'll look into that in a minute.

Alright I'll keep my eyes on this PR then

Comment (QbDesu) [reply renderer/src/modules/core.js]: Okay, fixed, I put the baseUrl into a variable so it it doesn't it isn't hardcoded in the strings over and over but forgot to add it back in in one spot. >.<'
